# Generated by Django 5.2.3 on 2026-04-30 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_subcategory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='user',
        ),
    ]
