# Generated by Django 5.2.6 on 2026-03-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_subcategory_user_alter_subcategory_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='user',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(),
        ),
    ]
