# Generated by GitHub Copilot
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_subcategory_user_alter_subcategory_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='image',
            field=models.ImageField(blank=True, upload_to='themes/'),
        ),
    ]
