# Generated by Django 5.2.3 on 2026-05-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_subcategory_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomSubcategory',
        ),
    ]
