# Generated by GitHub Copilot
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_subcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='video',
            field=models.FileField(blank=True, upload_to='subcategories/videos/'),
        ),
    ]
